version: '3.2'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - SA_PASSWORD=Unicam123!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    networks:
      - net

networks:
  net:
